version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn test
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
workflows:
  version: 2
  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build